/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GorevYoneticisi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Library {
	
	public static void main (String [] args ) throws ClassNotFoundException, SQLException{
		
		System.out.println("calistim");
        String connectionUrl = "jdbc:mysql://localhost:3306/gorevler?useUnicode=true&characterEncoding=UTF-8&user=sulefdnl&password=password";
        Connection conn = DriverManager.getConnection(connectionUrl);
        ResultSet rs = conn.prepareStatement("show tables").executeQuery();
 
        while(rs.next()){
            String s = rs.getString(1);
            System.out.println(s);
        }
    }
}
