/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GorevYoneticisi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;

import controller.GorevController;
import controller.KisiController;

public class Main {
	
	public static void main (String [] args ) throws ClassNotFoundException, SQLException{
		
		Scanner scanner = new Scanner(System.in);
		System.out.println("görevler için 1 kiþiler için 2 ye basýnýz.");
		int secim = scanner.nextInt();
		if(secim==1){
			GorevController gorevController = new GorevController();
			gorevController.gorev();
			}
		if(secim==2) {
			KisiController kisiController = new KisiController();
			kisiController.Kisi();
		}
    }
	
	
	
}
