/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GorevYoneticisi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import controller.GorevController;

public class Main {
	
	public static void main (String [] args ) throws ClassNotFoundException, SQLException{
		GorevController gorevController = new GorevController();
		gorevController.gorev();
		
		System.out.println("calistim");
        String connectionUrl = "jdbc:mysql://localhost:3306/gorevler?useUnicode=true&characterEncoding=UTF-8&user=sulefdnl&password=sF23.07.2000";
        Connection conn = DriverManager.getConnection(connectionUrl);
        ResultSet rs = conn.prepareStatement("select * from gorev").executeQuery();
 
        while(rs.next()){
            String s = rs.getString(1);
            System.out.println(s);
            String s2 = rs.getString(2);
            System.out.println(s2);
            String s3 = rs.getString(3);
            System.out.println(s3);
            String s4 = rs.getString(4);
            System.out.println(s4);
        }
    }
}
